<?php

declare(strict_types=1);

return [
    'tenant_routes' => [
        'GET /api/v1/members' => 'core.member.read',
        'POST /api/v1/members' => 'core.member.create',
        'GET /api/v1/members/{member_id}' => 'core.member.read',
        'GET /api/v1/members/{member_id}/effective-access' => 'core.member.effective-access.read',
        'PATCH /api/v1/members/{member_id}' => 'core.member.update',
        'PUT /api/v1/members/{member_id}/roles' => 'core.member.role.assign',
        'POST /api/v1/members/{member_id}/suspend' => 'core.member.suspend',
        'POST /api/v1/members/{member_id}/activate' => 'core.member.activate',
        'POST /api/v1/members/{member_id}/leave' => 'core.member.leave',
        'GET /api/v1/departments' => 'core.department.read',
        'POST /api/v1/departments' => 'core.department.create',
        'GET /api/v1/departments/{department_id}' => 'core.department.read',
        'PATCH /api/v1/departments/{department_id}' => 'core.department.update',
        'POST /api/v1/departments/{department_id}/move' => 'core.department.move',
        'POST /api/v1/departments/{department_id}/archive' => 'core.department.archive',
        'GET /api/v1/roles' => 'core.role.read',
        'POST /api/v1/roles' => 'core.role.create',
        'GET /api/v1/roles/{role_id}' => 'core.role.read',
        'PATCH /api/v1/roles/{role_id}' => 'core.role.update',
        'POST /api/v1/roles/{role_id}/archive' => 'core.role.archive',
        'PUT /api/v1/roles/{role_id}/permissions' => 'core.role.permission.assign',
        'GET /api/v1/permissions' => 'core.permission.read',
        'GET /api/v1/modules' => 'core.module.read',
        'PATCH /api/v1/modules/{module_key}/config' => 'core.module.configure',
        'GET /api/v1/audit-events' => 'core.audit.read',
        'GET /api/v1/audit-events/{event_id}' => 'core.audit.read',
        'GET /api/v1/menu-diagnostics' => 'core.role.read',
    ],
    'platform_routes' => [
        'GET /api/platform/v1/tenants' => 'platform.tenant.read',
        'POST /api/platform/v1/tenants' => 'platform.tenant.create',
        'GET /api/platform/v1/tenants/{tenant_id}' => 'platform.tenant.read',
        'PATCH /api/platform/v1/tenants/{tenant_id}' => 'platform.tenant.update',
        'POST /api/platform/v1/tenants/{tenant_id}/owner-candidates' => 'platform.tenant.provision-owner',
        'POST /api/platform/v1/tenants/{tenant_id}/owner-candidates/{member_id}/activate' => 'platform.tenant.provision-owner',
        'POST /api/platform/v1/tenants/{tenant_id}/activate' => 'platform.tenant.lifecycle',
        'POST /api/platform/v1/tenants/{tenant_id}/suspend' => 'platform.tenant.lifecycle',
        'POST /api/platform/v1/tenants/{tenant_id}/close' => 'platform.tenant.lifecycle',
        'PUT /api/platform/v1/tenants/{tenant_id}/modules/{module_key}' => 'platform.tenant.module.manage',
        'DELETE /api/platform/v1/tenants/{tenant_id}/modules/{module_key}' => 'platform.tenant.module.manage',
        'GET /api/platform/v1/operators' => 'platform.operator.read',
        'POST /api/platform/v1/operators' => 'platform.operator.create',
        'GET /api/platform/v1/operators/{operator_id}' => 'platform.operator.read',
        'PATCH /api/platform/v1/operators/{operator_id}' => 'platform.operator.update',
        'POST /api/platform/v1/operators/{operator_id}/suspend' => 'platform.operator.lifecycle',
        'POST /api/platform/v1/operators/{operator_id}/activate' => 'platform.operator.lifecycle',
        'POST /api/platform/v1/operators/{operator_id}/close' => 'platform.operator.lifecycle',
        'PUT /api/platform/v1/operators/{operator_id}/roles' => 'platform.operator.role.assign',
        'GET /api/platform/v1/roles' => 'platform.role.read',
        'POST /api/platform/v1/roles' => 'platform.role.create',
        'GET /api/platform/v1/roles/{role_id}' => 'platform.role.read',
        'PATCH /api/platform/v1/roles/{role_id}' => 'platform.role.update',
        'POST /api/platform/v1/roles/{role_id}/archive' => 'platform.role.archive',
        'PUT /api/platform/v1/roles/{role_id}/permissions' => 'platform.role.permission.assign',
        'GET /api/platform/v1/permissions' => 'platform.permission.read',
        'GET /api/platform/v1/audit-events' => 'platform.audit.read',
        'GET /api/platform/v1/audit-events/{event_id}' => 'platform.audit.read',
        'GET /api/platform/v1/menu-diagnostics' => 'platform.role.read',
        'GET /api/platform/v1/upgrade' => 'platform.upgrade.read',
        'GET /api/platform/v1/ops/status' => 'platform.ops.read',
        'GET /api/platform/v1/ops/maintenance' => 'platform.ops.read',
        'PUT /api/platform/v1/ops/maintenance' => 'platform.ops.maintenance.manage',
        'POST /api/platform/v1/ops/maintenance/{maintenance_key}/close' => 'platform.ops.maintenance.manage',
        'POST /api/platform/v1/ops/tasks/backup' => 'platform.ops.backup.manage',
        'POST /api/platform/v1/ops/tasks/restore' => 'platform.ops.restore.manage',
        'GET /api/platform/v1/ops/tasks/{task_key}' => 'platform.ops.read',
        'GET /api/platform/v1/ops/logs' => 'platform.ops.logs.read',
    ],
];
